default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: api_development
  # Optional: local username/password
  # username: api
  # password:
  # host: localhost
  # port: 5432

test:
  <<: *default
  database: api_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  # SSL is required for Render PostgreSQL
  sslmode: require
