default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: api_development

test:
  <<: *default
  database: api_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  sslmode: require

  # Optional connections used by Rails for Action Cable, caching, and background jobs
  cable:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
    sslmode: require

  cache:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
    sslmode: require

  queue:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
    sslmode: require
